name: olderos_launcher
description: "OlderOS - Sistema operativo per anziani"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.16.3
  url_launcher: ^6.3.1
  file_picker: ^8.0.0
  shared_preferences: ^2.2.0
  enough_mail: ^2.1.6
  http: ^1.2.0
  path_provider: ^2.1.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
